photoshare/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from app import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('loginUser/', views.loginUser, name='login'),
    path('registerUser/', views.registerUser, name='register'),
    path('logoutUser/', views.logoutUser, name='logout'),
    path('add/', views.addPhoto, name='add'),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name
    

class Photo(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='02_image_uploader_pro/images')

    # def __str__(self):
    #     return self.image

app/forms.py
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User

class register(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class customLogin(AuthenticationForm):
    pass

app/views.py
from django.shortcuts import render
from .forms import register, customLogin
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from .models import Category, Photo

# Create your views here.
def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    
    else:
        if request.method == 'POST':
            form = customLogin(request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user_obj = authenticate(username=uname, password=upass)

                if user_obj is not None:
                    login(request,user_obj)
                    return HttpResponseRedirect('/')
                
        form = customLogin()
        
    return render(request, 'login_register.html', context={'form':form, 'page':page})


def registerUser(request):
    page = 'register'
    
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    
    else:
        if request.method == 'POST':
            form = register(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/')
            
        form = register()
    
    return render(request, 'login_register.html',context={'form':form, 'page':page})


def logoutUser(request):
    logout(request)
    return HttpResponseRedirect('/')



# second part
def home(request):
    category = request.GET.get('category')
    user = request.user

    if category == None:
        photos = Photo.objects.all()
    else:
        photos = Photo.objects.filter(category__name = category)

    categories = Category.objects.all()
    return render(request, 'gallery.html', context={'categories':categories, 'photos':photos})




def addPhoto(request):
    user = request.user
    # categories = user.category_set.all()
    
    categories = Category.objects.all()

    if request.method == 'POST':
        data = request.POST
        image = request.FILES.get('images')
        print(data) ,print(image)

        if data['category'] != 'none':
            category = Category.objects.get(name=data['category'])
        
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(user=user,name=data['category_new'])
        
        else:
            category = None
        
        photo = Photo.objects.create(
            category = category,
            image = image
        )
        return HttpResponseRedirect('/')

    return render(request, 'add.html', context={"categories":categories})




def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

app/templates/about.html
{% extends 'index.html' %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
<div class="section">
    <h2>About</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus rerum sapiente esse laudantium eum excepturi
        illum fuga consequuntur dicta eveniet!</p>
</div>
{% endblock %}

app/templates/add.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Add Image{% endblock %}

{% block content %}
<div class="section">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <a href="{% url 'home' %}" class="btn btn-dark my-3">Go Back</a>
            <div class="card">


                <form method='POST' action="" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group m-3">
                        <label>Select a category</label>
                        <select name="category" class="form-control">
                            <option value='none'>Select a category...</option>

                            <!--  -->
                            {% for category in categories %}
                            <option value='{{category.name}}'>{{category.name}}</option>
                            {% endfor %}
                            <!--  -->
                            

                        </select>
                    </div>


                    <div class="form-group m-3">
                        <label>Create a new category</label>
                        <input name="category_new" type="text" placeholder="Create a new category" class="form-control">
                    </div>

                    
                    <div class="form-group m-3">
                        <label>Upload image</label>
                        <input required name="images" type="file" multiple class="form-control-file">
                    </div>

                    <button type='submit' class="btn btn-primary m-3">Submit</button>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/contact.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Contact{% endblock %}

{% block content %}
    <div class="section">
        <p>If you have any problem contact me at <a href="mailto:rahulsrajput29@gmail.com">rahulsrajput29@gmail.com</a></p>
    </div>
{% endblock %}

app/templates/gallery.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Wallpapers{% endblock %}

{% block content %}
<style>
    .list-group-item a {
        text-decoration: none;
        color: black;
    }

    .img-thumbnail {
        height: 200px;
        object-fit: cover;
    }
</style>

<div class="section">

    <div class="row">
        <div class="col-md-3 mb-5">
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'home' %}">All</a></li>
                
                {% for category in categories %}
                <li class="list-group-item"><a href="{% url 'home' %}?category={{category.name}}">{{category.name}}</a></li>
                {% endfor %}

            </ul>
        </div>


        <div class="col-md-9">

            <div class="row">

                {% for photo in photos %}
                <div class="col-md-4">
                    <a href="{{photo.image.url}}" target="_blank" class="d-block mb-4 h-100">
                        <img class="img-fluid img-thumbnail" src="{{photo.image.url}}"
                            alt="image">
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link type="image/png" sizes="96x96" rel="icon" href="{% static 'image/icons8.png' %}">


    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght,HEXP@160..700,22.3&display=swap"
        rel="stylesheet">
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- MDB -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light p-2">
        <div class="container">

            <!-- logo -->
            <a class="navbar-brand fs-4" href="{% url 'home' %}">Wallpapers</a>
            <!--  -->
            <!-- <a class="navbar-brand fs-4" href="{% url 'home' %}">Admin</a> -->
            <!--  -->


            <!-- toggle-button -->
            <button class="navbar-toggler shadow-none border-0" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- sidebar -->
            <div class="sidebar offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel1">

                <!-- sidebar header -->
                <div class="offcanvas-header text-black border-bottom">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel1">Wallpapers</h5>

                    <button type="button" class="btn-close btn-close-black shadow-none" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>

                </div>

                <!-- sidebar body -->
                <div class="offcanvas-body d-flex flex-column p-4 p-lg-0 flex-lg-row">
                    <ul class="navbar-nav justify-content-center align-items-center fs-5 flex-grow-1 pe-3">
                        <!--  -->
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="#">{{request.user | capfirst}}</a>
                        </li>
                        {% else %}
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="#">Guest</a>
                        </li>
                        {% endif %}
                        

                        <!--  -->
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                        </li>
                        <!--  -->
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                        </li>

                        

                        {% if user.is_authenticated %}
                        
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>


                        {% else %}
                        
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'login' %}">Login/Register</a>
                        </li>
                        
                        {% endif %}

                        {% if perms.app.add_photo %}
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'add' %}">Add Photo</a>
                        </li>
                        {% endif %}
                        
                    </ul>

                    <!-- github -->
                    <div class="d-flex flex-column justify-content-center align-item-center gap-3">
                        <a href="https://github.com/rahulsrajput/" target="_blank"><img src="{% static 'image/github.png' %}" alt=""
                                class="img-fluid logo"></a>
                    </div>
                </div>
            </div>
        </div>
    </nav>


    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>

app/templates/login_register.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Login/Register{% endblock %}

{% block content %}

<!-- login -->
{% if page == 'login' %}
<div class="section">
    <div class="mt-5 mb-2">
        <h3>Login</h3>
    
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Login" class="btn btn-dark">
        </form>
    </div>
    <p>Not have a account Register here <a href="{% url 'register' %}">Register</a></p>
</div>
{% endif %}


<!-- register -->
{% if page == 'register' %}
<div class="section">
    <div class=" mt-5 mb-2">
        <h3>Register</h3>
      
        <form action="" method="post">
          {% csrf_token %}
          {{form.as_p}}
          <input type="submit" value="Register" class="btn btn-dark">
        </form>
      </div>
    <p>Have account Login <a href="{% url 'login' %}">Login</a></p>
</div>
{% endif %}


{% endblock %}